### PR TITLE
[KERNEL-ESTIMATOR] [poig] [2022-11-1]

### PR DESCRIPTION
**Pull request by poig**
### Team members
Tan Jun Liang

### Submission summary
Private submission : `kernel_estimator.ipynb`
qBraid account: [laolianglaoliang@gmail.com](mailto:laolianglaoliang@gmail.com)
edit: I made a mistake in maximal deviation, I was confused by the paper, just fixed it, plz correct me if I am wrong there.

### Additional comments
Not sure why my Qbraid Kernel dying, after not running anything for a while.
Thanks for the challenge and all your hard work on this.

### CODE REVIEW

**Review by ryanhill1 — CHANGES_REQUESTED** [review]
Thanks for your submission! You currently have uncommitted changes on your `main` branch, so I'm not able to checkout your `kernel-estimation` branch. Can you please commit your changes so I can review your notebook in the correct branch? (You can commit changes without pushing to keep your changes private)

**Comment by ryanhill1** [comment]
@poig I'm sorry about the kernel dying, that's annoying. Could you tell me a little more about what's going on? E.g. do you know roughly how much time after not running anything the kernel dies? Is it on the order of minutes or hours?

**Comment by poig** [comment]
> Thanks for your submission! You currently have uncommitted changes on your `main` branch, so I'm not able to checkout your `kernel-estimation` branch. Can you please commit your changes so I can review your notebook in the correct branch? (You can commit changes without pushing to keep your changes private)

sorry, I am not sure, do you mean on qbraid git(I didn't use it before)? I just commit something; can you see it now?

**Comment by ryanhill1** [comment]
@poig Now I see it is set to the `kernel` branch. Is that correct? The `kernel-estimator` branch is still not visible, which one would you like me to review? Since it's a private submission, you could also just commit your changes to `main`.

**Comment by poig** [comment]
> @poig I'm sorry about the kernel dying, that's annoying. Could you tell me a little more about what's going on? E.g. do you know roughly how much time after not running anything the kernel dies? Is it on the order of minutes or hours?

yes, its randomly, sometimes after 15-45+minute

**Comment by poig** [comment]
> @poig Now I see it is set to the `kernel` branch. Is that correct? The `kernel-estimator` branch is still not visible, which one would you like me to review? Since it's a private submission, you could also just commit your changes to `main`.

so you can see my qbraid folder now? you can look at poig/HAQS-2022/qml-classifier-challenge/kernel_estimator.ipynb

**Comment by ryanhill1** [comment]
@poig Ohhh, yep I can see it now, thank you! Will review shortly.

**Comment by poig** [comment]
> @poig Ohhh, yep I can see it now, thank you! Will review shortly.

remember to change the folder save location if you want to save file, I didn't change it.

**Review by ryanhill1 — COMMENTED** [review]
Thanks for your submission! Your kernel estimator solution satisfies all of our requirements regarding Algorithms 1 & 2, and tested at **100%** accuracy. Together with your VQC submission, you are now the overall leader and **1st** on the leaderboard. 

In addition, the way you've implemented `kernel_experimental()`, `dualqp()` and `dualSVM()` is incredibly clean and clear, and your recreation of plot 4B is an excellent touch!

**Comment by poig** [comment]
> @poig I'm sorry about the kernel dying, that's annoying. Could you tell me a little more about what's going on? E.g. do you know roughly how much time after not running anything the kernel dies? Is it on the order of minutes or hours?

Its not only kernel, also the lab server("Server unavailable or unreachable"), and give 503, when I click restart.

**Comment by ryanhill1** [comment]
@poig Oh, yep. We were made aware of this today. It was caused by high volumes of traffic to Lab that our servers weren't ready for. Nearing the end of the hackathon and a lot of people are online. We made some updates in the last couple of hours that should fix the problem, so lmk if the issue persists. But it should be better. Sorry again about that!

**Pull request closed without merging**
