### PR TITLE
[VQC-CHALLENGE] [qubytes] [2022-11-4]

### PR DESCRIPTION
**Pull request by Rick0317**
### Team members
Emily, Kabir, Rick, Frroggiee
### Submission summary
Modified the kernel estimator file and small configuration in VQC file
contact: rick.hey.huang@gmail.com

### CODE REVIEW

**Comment by ryanhill1** [comment]
@Rick0317 So is this submission for both the kernel estimator and vqc challenges? Or just the vqc?

**Comment by Rick0317** [comment]
This is for both kernel estimator and vqc challenges, but if we are not allowed to do them at once, could you just think of it as the submission for the kernel estimator?

**Comment by ryanhill1** [comment]
> This is for both kernel estimator and vqc challenges, but if we are not allowed to do them at once, could you just think of it as the submission for the kernel estimator?

Nope you can definitely submit to both! Just double checking since the PR title only said VQC-CHALLENGE, but your comment mentioned the kernel estimator.

**Comment by Rick0317** [comment]
Ok!  Thank you!

**Comment by ryanhill1** [comment]
@Rick0317 Thank you team qubytes for participating in the hackathon! Your final submission achieved **73%** accuracy with a quantum cost of **111**. Since your previous model achieved 100% accuracy, this accuracy score and its associated quantum cost of 356.25 stood and were not replaced on the leaderboard. Also, thank you for your submission to the kernel estimator challenge! Your kernel estimator model achieved ~60% accuracy. Between both submissions, your team ranked **12th** overall on the leaderboard! If you haven't already, we would really appreciate it if you filled out our [exit survey](https://5srcuajybw1.typeform.com/to/dAVUiQKY). Additionally, I'd love to stay in touch as you continue your journey through quantum, so feel free to reach out to me directly on Discord (ryanhill1#5643), via email (ryanhill@qbraid.com), or on [LinkedIn](https://www.linkedin.com/in/ryan-james-hill/)!

**Pull request closed without merging**
