### PR TITLE
[VQC-CHALLENGE] [ObjectivityLtd] [03.11.2022, 04.11.2022]

### PR DESCRIPTION
**Pull request by mbaczyk123**
### Team members
Michal Baczyk
Peter den Haan

### Submission summary
Trying to lower the quantum cost. 
Private mode. qBraid account registered for mbaczyk@objectivity.co.uk
Please review two notebooks. One is for submission on 03.11.2022 and the other on 04.11.2022. 
HAQS-2022/qml-classifier-challenge/vqc_challenge.ipynb
HAQS-2022/qml-classifier-challenge/vqc_challenge-Copy1.ipynb

### CODE REVIEW

**Comment by mbaczyk123** [comment]
@ryanhill1 I will be grateful if you could get back to me with the accuracy scores achieved by these models. For me, they were consistently equal to 100%.

**Comment by mbaczyk123** [comment]
@ryanhill1 Btw, what is the number of n_samples that you used to test our model and other teams' models? We thought that it is not possible to change this number.

**Comment by ryanhill1** [comment]
@mbaczyk123 Hi Michal thanks for reaching out, I'm happy to provide more clarity. 

When we evaluate the models, we do not load your saved weights from past training. Instead, we train/test the models from scratch against our judging data set, which is generated using the same `gen_binary.py` that you have access to. And yes, for all of the judging, we set `n_samples = 1000` with a train/test split of 0.8. 

For your group, we evaluated both of the files you gave (`vqc_challenge.ipynb` and `vqc_challenge-Copy1.ipynb`) which we usually don't do. While your models did improve the quantum cost compared to your last submission, neither model could consistently achieve 100% accuracy. In fact, for these notebooks, we recorded accuracy scores as low as **80%**.

Compared to your previous submissions, I was skeptical of this result, so I actually re-checked that I was on the appropriate branch, re-copied the files over, and trained both models again. However, the results were similarly sub-optimal. Out of curiosity, I generated a new data set using the script, ran both models again, and got back the same range of accuracy scores, consistently _below_ 100%.

Many teams suffered a similar dip in accuracy on their final submission In an attempt to lower their quantum cost. If any of the teams in the final top 3 (Qualition, Kossakowski, or Feynman-Prodigies) choose to release their solution, I would encourage you to take a look! Each of their approaches dynamically varied the number of training iterations based on how their model's test accuracy was improving over each iteration (or not). E.g. in addition to optimizing the training procedure itself, they would not break out of their training loop until 100% accuracy was achieved multiple times. To me, this seemed like the best approach to ensuring consistent accuracies regardless of the number of samples or differences in data sets.

Please let me know if you have any further questions, I would happy to answer!

**Comment by mbaczyk123** [comment]
What do you mean by that? "Each of their approaches dynamically varied the number of training iterations based on how their model's test accuracy was improving over each iteration (or not)."
Are you saying that the teams you mention evaluated the model accuracy during training on test dataset?

**Comment by ryanhill1** [comment]
> What do you mean by that? "Each of their approaches dynamically varied the number of training iterations based on how their model's test accuracy was improving over each iteration (or not)." Are you saying that the teams you mention evaluated the model accuracy during training on test dataset?

The approaches varied, and I don't remember the specifics. But for each of the top groups, I remember that the number of training iterations was not fixed, and instead depended on the current loss at each iter, a running tally of the quantum cost, and/or other factors. For exact details, I would encourage you to reach out to the teams themselves, and see if they are willing to share their notebooks.

**Comment by mbaczyk123** [comment]
@ryanhill1  "Each of their approaches dynamically varied the number of training iterations based on how their model's test accuracy was improving over each iteration (or not)." - this is very important. If this is the case, then it makes an ivalid ml approach since you cannot access test dataset in any way during the training. It is as if you were training on test dataset. Please verify these for the top submissions.

**Comment by ryanhill1** [comment]
> @ryanhill1 "Each of their approaches dynamically varied the number of training iterations based on how their model's test accuracy was improving over each iteration (or not)." - this is very important. If this is the case, then it makes an ivalid ml approach since you cannot access test dataset in any way during the training. It is as if you were training on test dataset. Please verify these for the top submissions.

No, they did not use the *test* data set. Each team had the same `gen_binary.py` script to go off of, and that is all. I can promise you that the judging was done fairly, and took into account a wide range of factors. Models were evaluated and run not just by myself, but by two other qBraid engineers as well, with the requirement that all three of us accept the solution as valid before it is considered for the leaderboard.

We did not disclose the judging data set for exactly this reason so models could not be trained particularly for that data. We are well aware of these boundaries and their impact on the validity of ML models.

**Comment by mbaczyk123** [comment]
Thank you for your explanations!

**Pull request closed without merging**
