### PR TITLE
[KERNEL-ESTIMATOR] [Qualition] [2022-10-31]

### PR DESCRIPTION
**Pull request by JohnGoldenGardiner**
### Team members

A.C.E07  
Avhijit_Nair  
John Gardiner  
rupeshknn  
Vishal Mandal  
youyaQ

### Submission summary

Private submission
qBraid account: johngoldengardiner@gmail.com

### CODE REVIEW

**Review by ryanhill1 — COMMENTED** [review]
Thanks for your submission! In your `kernel_circuit()` function, you are returning the probability of each computational basis state, when in fact you want to return `shots` number of Z-basis measurement samples. In your `kernel()` function, you then want to construct the kernel estimate following steps 10-14 in "Algorithm 1: training" to loop through the individual samples, increment the counter, and divide the final count by the number of shots. For a simulator, getting the probabilities is conceptually doing the same thing. However, if we were using actual quantum hardware we would be sampling, which is the experimental approach we want to replicate. Aside from that, the way you've solved the SVM looks very good. Let me know if you have any questions!

**Comment by JohnGoldenGardiner** [comment]
Just to clarify, I've set up the qnode so that it returns "probabilities" based on doing 50000 shots. It's actually not returning probabilities, but rather is sampling 50000 times from the true probability distribution. It does not return the analytic result.

My understanding is that you only get the analytic result if you fail to include a shots argument when defining the device. If you do include a number of shots, then qml.probs(), qml.expval(), etc. return statistics based on sampling.

**Comment by JohnGoldenGardiner** [comment]
Sorry for the question, but I'm still not sure I understand your feedback. Would, say, qml.counts() in lieu of qml.probs() be acceptable? My understanding was that qml.probs() does the same thing as qml.counts, just with a division by the number of shots. Is that not correct?

**Comment by ryanhill1** [comment]
@JohnGoldenGardiner Sorry for my delayed response! On the user side, the end result is the same, so it is a formality. But behind the scenes, the queued request to the backend contains the desired observable return type, so we want to be consistent with the given training algorithm. If we were solving the problem for a non-academic purpose, then it wouldn't matter. But just like we're asking that you explicitly write out the loss function and solve for the support vector weights instead of using all the presets with `SVC.fit`, we want you to explicitly iterate through the samples and increment a counter for the measurements in the zero-state instead of using `qml.probs`. For this, it's most idiomatic to use `qml.sample`. Let me know if I can answer any other questions!

**Pull request closed without merging**
