### PR TITLE
[VQC-CHALLENGE] [TheQuantumSquad007] [02.11.2022]

### PR DESCRIPTION
**Pull request by HandyKurniawan**
### Team members
Zentz#5399
Tyy#5960
Terkasaurus#6388
fcodelrio#2239
Gehad Salem#7458
saraok#9644

### Submission summary
reduced the overall QuantumCost while maintaining 100% accuracy

### Additional comments
Please see the code under the email [handykhandy@gmail.com](mailto:handykhandy@gmail.com) account in the qBraid Lab
File: vqc_challenge.ipynb

### CODE REVIEW

**Comment by HandyKurniawan** [comment]
Tested with 100% and cost 44.4 :)
Hope this will work

**Comment by HandyKurniawan** [comment]
Quantum_Simulator_run

I ran in the quantum simulator, but it gave me an error and the file were not saved :(

**Comment by HandyKurniawan** [comment]
image

**Review by ryanhill1 — APPROVED** [review]
Thanks for your submission! Your model achieved **100%** accuracy on our judging data set with a quantum cost of **122.1**, which currently ranks as the **2nd** lowest quantum cost on the leaderboard. 
Screen Shot 2022-11-03 at 9 34 29 AM

**Comment by HandyKurniawan** [comment]
Thanks, @ryanhill1! I have a question, do you use the same dataset or change it every time you do the testing? 

You don't have to answer if this is confidential.

**Comment by ryanhill1** [comment]
> Thanks, @ryanhill1! I have a question, do you use the same dataset or change it every time you do the testing?
> 
> You don't have to answer if this is confidential.

Screen Shot 2022-11-03 at 3 05 30 PM

**Comment by HandyKurniawan** [comment]
ahh yeah i forgot about that, thanks!!

**Pull request closed without merging**
