### PR TITLE
[VQC-CHALLENGE/KERNEL-ESTIMATOR] [CQTech] [4th Nov, 2022]

### PR DESCRIPTION
**Pull request by mmlongh**
### Team members

https://cqtech.org

Mohamed Messaoud Louamri @mmlouamri
Nacer eddine Belaloui @Belaloui
Abdellah Tounsi @Abduhu 
Taha Rouabah @Taha-Rouabah

### Submission summary
The submission summary can be found at the top of each notebook

### CODE REVIEW

**Review by Abduhu — APPROVED** [review]

**Review by Abduhu — APPROVED** [review]
Good results

**Review by Taha-Rouabah — COMMENTED** [review]
Hope this will not be the best try !

**Review by Taha-Rouabah — APPROVED** [review]
Hope this will not be the best try !

**Comment by ryanhill1** [comment]
@mmlouamri Thank you CQTech for your submission and for all your help during the hackathon! Your final VQC model achieved **100%** accuracy with a quantum cost of **77.7**, which would have ranked your team **4th** overall on the leaderboard! (Ricky told me your team asked not to be ranked, which is why your score wasn't listed). Additionally, your kernel estimator solution looked awesome, and also achieved 100% accuracy. The inclusion of the swap test at the end was great, and you might have been the only group to do it correctly :) I'd love to stay in touch, so feel free to reach out to me directly on Discord (ryanhill1#5643), via email (ryanhill@qbraid.com), or on [LinkedIn](https://www.linkedin.com/in/ryan-james-hill/) anytime!

**Pull request closed without merging**
