### PR TITLE
[KERNEL-ESTIMATION] [TheQuantumSquad007] [02.11.2022]

### PR DESCRIPTION
**Pull request by HandyKurniawan**
### Team members
Zentz#5399
Tyy#5960
Terkasaurus#6388
fcodelrio#2239
Gehad Salem#7458
saraok#9644

### Submission summary
Try QKE the first time. Check the file under handykhandy@gmail.com
File name: kernel_estimator_handy.ipynb

### Additional comments
accuracy 65%

### CODE REVIEW

**Comment by HandyKurniawan** [comment]
updated accuracy 100%

**Comment by HandyKurniawan** [comment]
image
got error while running it in the Quantum simulator :(

**Review by ryanhill1 — CHANGES_REQUESTED** [review]
Thanks for your submission! The way you solve for the support vectors looks correct and is very elegantly done using your `objective_function()` and `SVM` class. I also really like how you've incorporated additional testing on a remote Braket device. There's one minor modification needed before I can record your result on the leaderboard: Right now, your `fidelity_estimate()` measures the `qml.expval`, which is inconsistent with Algorithm 1. The ideal kernel is constructed using inner products, while the experimental kernel must be constructed by sampling. Your `fidelity_estimate()`, therefore, should return either `qml.sample` or `qml.counts`. After this change is made, then your submission can be accepted.

**Comment by HandyKurniawan** [comment]
Thank you for the tips, should I submit a new PR or will you consider this PR after I change? I think this is a minor change I will do it asap :)

**Comment by HandyKurniawan** [comment]
also, I have a question, I am thinking `qml.expval` that this function should return an expectation value, right? https://docs.pennylane.ai/en/stable/code/api/pennylane.expval.html

and the expectation value of the classification problem should be r / R which is the algorithm in line 14.

because if I change the shot into 1, the result will be only 0 and 1. if I change the shots into 2, then 0, 0.5, and 1.

I still don't understand why we cannot use the qml.expval while this is also a measurement in a Z basis (using the projector of |00><00|). So, this is already the same as algorithm 1, but why should we use samples or counts?

**Comment by ryanhill1** [comment]
@HandyKurniawan You are correct that in the end, the two are mathematically equivalent. However, the intention here is that we are trying to mirror the experimental training algorithm. We are implementing the algorithm with its original purpose in mind, which was to interface directly with quantum hardware. Experimentally, you would read out the individual measurement samples one at a time, and process the results as you go.

**Comment by HandyKurniawan** [comment]
@ryanhill1 Noted! Thank you for the explanations! I have fixed the function! 

Also maybe a hint for algorithm 1 would be helpful because I don't know if we need to sample separately. I thought the `qml.expval()` is enough.

**Comment by ryanhill1** [comment]
> @ryanhill1 Noted! Thank you for the explanations! I have fixed the function!
> 
> Also maybe a hint for algorithm 1 would be helpful because I don't know if we need to sample separately. I thought the `qml.expval()` is enough.

No problem, I'll try to review your update before the end of the day since your original PR was before the cutoff. Yeah, in hindsight maybe a hint should have been given there. But in writing the challenge, we just thought that how Algorithm 1 explicitly loops through each shot and increments a counter sort of already hinted at using samples instead of expectation values.

**Comment by HandyKurniawan** [comment]
> > @ryanhill1 Noted! Thank you for the explanations! I have fixed the function!
> > Also maybe a hint for algorithm 1 would be helpful because I don't know if we need to sample separately. I thought the `qml.expval()` is enough.
> 
> No problem, I'll try to review your update before the end of the day since your original PR was before the cutoff. Yeah, in hindsight maybe a hint should have been given there. But in writing the challenge, we just thought that how Algorithm 1 explicitly loops through each shot and increments a counter sort of already hinted at using samples instead of expectation values.

Thanks, @ryanhill1 really appreciate it! 

At first, I was following the algorithm by looping it.. but then, when I analyzed the circuit and other stuff from the ideal, I realized mathematically they are the same :D

**Comment by ryanhill1** [comment]
@HandyKurniawan Just checked the updates and they look good! I've updated the leaderboard with your score. Your team is now eligible to be considered for the overall QML Challenge winner, which will be judged not just on the leaderboard ranking, but also on the overall impression of both your VQC and kernel estimator submissions.

**Pull request closed without merging**
