### PR TITLE
[KERNEL-ESTIMATOR] [CSDL] [22.11.02]

### PR DESCRIPTION
**Pull request by dohun-qml**
### Team members
dohun#9207
sunghye#7199
Jaekyung Im#3958

### Submission summary
private submission
qbraid account: dohunkim@postech.ac.kr

### Additional comments
Includes modifications based on the feedback of previous PR #32

### CODE REVIEW

**Review by ryanhill1 — COMMENTED** [review]
Thanks for your submission! Your implementation of Algorithm 2 looks spot on, and most of Algorithm 1 looks correct as well! I have one question: In Algorithm 1, steps 17-18, we want to optimize $\alpha$ in the equation $L_D$. In Cell 18, I see that you solve for the $\alpha$s using `cvxopt.solvers.qp`, but I don't see where in this process the equation $L_D$ is considered, which is what we're trying to minimize. If you do already account for  $L_D$ during training, could you explain how? If you don't, that would be the last thing to work on before I can accept the submission.

**Comment by dohun-qml** [comment]
@ryanhill1 Sorry, I should have added a more detailed explanation. L_D is directly implemented into the objective function of the quadratic problem, which means the first term of L_D (sum of alpha) forms the matrix 'q', and the second term of L_D forms the matrix 'P'. Since the standard form of the QP is to minimize the objective function, the sign of these two matrices have been flipped. Is it possible to write the additional explanation of this with markdown after accept? Thank you for you feedback.

**Comment by ryanhill1** [comment]
> @ryanhill1 Sorry, I should have added a more detailed explanation. L_D is directly implemented into the objective function of the quadratic problem, which means the first term of L_D (sum of alpha) forms the matrix 'q', and the second term of L_D forms the matrix 'P'. Since the standard form of the QP is to minimize the objective function, the sign of these two matrices have been flipped. Is it possible to write the additional explanation of this with markdown after accept? Thank you for you feedback.

Ok, gotcha! Thanks, yeah could you write that out in markdown? And then let me know once you are finished. In the meantime, I'll hold your submission at the front of my review queue.

**Comment by dohun-qml** [comment]
@ryanhill1 I finished updating my notebook `kernel_estimator.ipynb`. The explanation of QP formulation is at between cell 17 and 18. Please note that the code of cell 18 has been partially changed to fit the newly written formula, but it is mathematically equivalent (e.g. replacing the element-wise multiplication by broadcasting, to matrix multiplication).

**Review by ryanhill1 — COMMENTED** [review]
Thanks for the updates! The markdown you've given for how you solve the quadratic program with CVXOPT is extremely clear and well done. Your implementation of the kernel estimator satisfies Algorithms 1 & 2 and achieved a test accuracy of **100%**. Your team is now eligible to be considered for the overall QML Challenge winner, which will be judged not just on the leaderboard ranking, but also on the overall impression of both your VQC and kernel estimator submissions. 

If you wanted to make any further updates for the remainder of the week, you could try to replicate Fig 4B as another way to show how close your kernel estimate is to the ideal:

Screen Shot 2022-10-31 at 2 43 12 PM

However, this is totally optional, and any additions you make after this point are just a bonus. Overall, great work!

**Pull request closed without merging**
