### PR TITLE
[KERNEL-ESTIMATOR] [The HaQers] [October 29 2022]

### PR DESCRIPTION
**Pull request by giorgosgiapis**
### Team members
Alfaxad#2840
E-PC#6747
flamethrower#5529
giorgosgiapis#0428
Luis Felipe Morales Bultron#0562
moustafa_zada#5306

### Submission summary
This is a private submission. Qbraid associated email: giorgosgiapis@mail.com

### CODE REVIEW

**Comment by ryanhill1** [comment]
Thanks for your submission, your updates look promising! Our team will review it in detail tomorrow and I will let you know if all requirements are fulfilled. As a reminder, this challenge will be evaluated both on the score and on the overall impression of the solution as outlined in the README. So if your accuracy score is accepted, your team will still have the opportunity to continue to add to your solution until the deadline if you wish.

**Comment by giorgosgiapis** [comment]
> Thanks for your submission, your updates look promising! Our team will review it in detail tomorrow and I will let you know if all requirements are fulfilled. As a reminder, this challenge will be evaluated both on the score and on the overall impression of the solution as outlined in the README. So if your accuracy score is accepted, your team will still have the opportunity to continue to add to your solution until the deadline if you wish.

Thanks for the reply! We have two questions: 
1) Will you report back on the accuracy of our solution after reviewing it?
2) When we update our notebook, do we have to open new PRs, or will the changes we make be visible to you?

**Comment by ryanhill1** [comment]
1. Yes, we'll let you know!
2. We'll be able to see the changes, so need no to open a second PR 👍

**Comment by ryanhill1** [comment]
Your solution looks great! Sorry for the delay in the review.  I will add your kernel estimator accuracy to the leaderboard. If you wanted to make any additional updates for the remainder of the week, here are a few things you could do if you wanted to:

1. In `fidelity_estimate`, you are returning `qml.sample()` without specifying a quantum observable. This means you are sampling in whatever computational basis the device uses by default. If we substituted an actual QPU for the local simulator, this would not always be guaranteed to be the `Z` basis, so could cause inconsistencies. See [qml.sample](https://docs.pennylane.ai/en/stable/code/api/pennylane.sample.html)
2. It would also be really cool if you tried to replicate Fig 4B and see how close yours looks to the original: Screen Shot 2022-10-31 at 2 43 12 PM
4. Add any comments that could be useful to someone reading your code for the first time who is unfamiliar with the procedure

**Comment by PCesteban** [comment]
Hi @ryanhill1, we also want to know if it is required to open another PR so you can check our updates based on your suggestions.

**Comment by ryanhill1** [comment]
Yes, that would be very helpful just so we can keep track better and don't forget.

**Pull request closed without merging**
