### PR TITLE
[VQC-CHALLENGE] [ObjectivityLtd] [02.11.2022]

### PR DESCRIPTION
**Pull request by mbaczyk123**
### Team members
Michal Baczyk
Peter den Haan

### Submission summary
Private mode. mbaczyk@objectivity.co.uk
HAQS-2022/qml-classifier-challenge/vqc_challenge-Copy1.ipynb

### CODE REVIEW

**Review by ryanhill1 — CHANGES_REQUESTED** [review]
Thanks for the update. You currently have uncommitted changes on your `ObjectivityTeam` branch, so I'm not able to checkout your `ObjectivityLtd` branch. Can you please commit your changes so I can review your notebook in the correct branch? (You can commit changes without pushing to keep your changes private)

**Comment by mbaczyk123** [comment]
I have just committed the changes without pushing them as suggested. I am working on the fork from [ObjectivityLtd:ObjectivityTeam](https://github.com/ObjectivityLtd/HAQS-2022) in the qBraid lab registed for the mbaczyk@objectivity.co.uk e-mail. 

I used my other fork as well but it seemed to make more confusion than any real help. Sorry about that and thank you for your kind suggestion how to improve. :)

**Comment by mbaczyk123** [comment]
@ryanhill1 Please review two solutions to VQC challenge from 01.11 and 02.11 in the current git status. :)

**Comment by ryanhill1** [comment]
@mbaczyk123 Thanks, I can see it now. Will review in the next couple hours.

**Comment by mbaczyk123** [comment]
@ryanhill1 Lovely, thank you very much! 

Please see both of the files since the previous PR was not adequate because of the issues with synchronization:
HAQS-2022/qml-classifier-challenge/vqc_challenge.ipynb
HAQS-2022/qml-classifier-challenge/vqc_challenge-Copy1.ipynb

**Review by ryanhill1 — COMMENTED** [review]
Thanks for your submission! Unfortunately, neither of the models I tested consistently tested at 100% accuracy. I trained/tested both models on two different data sets, and evaluated the accuracy of each model 20 times and these were my results:

`vqc_challenge.ipynb`:

Screen Shot 2022-11-02 at 4 56 10 PM

Screen Shot 2022-11-02 at 4 58 04 PM

`vqc_challenge-Copy1.ipynb`:

Screen Shot 2022-11-02 at 4 59 54 PM

Screen Shot 2022-11-02 at 5 01 49 PM

They were both very close but were not consistent enough for me to accept the submission. However, your previous submission's quantum cost score of 91.5 still stands as the lowest quantum cost on the leaderboard.

**Pull request closed without merging**
